<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| User Repositiory Messages
	|--------------------------------------------------------------------------
	*/

	'headprivacy' 		=>  "Política de Privacidade",

	'head2privacy' 		=>	"Acerca do SponzorMe:",

	'head3privacy'		=>	"A nossa política:",

  'head4privacy' 		=>  "Consentimento:",

	'head5privacy' 		=>	"Informações que recolhemos:",

	'head6privacy'		=>	"1. Dados Pessoais:",

  'head7privacy' 		=>  "2. Dados Não Pessoais:",

	'head8privacy' 		=>	"3. Cookies, Pixel Tags, Objetos Locais Partilhados, Armazenamento na Web e Tecnologias Semelhantes:",

	'head9privacy'		=>	"Utilização das informações que recolhemos:",

  'head10privacy' 		=>  "1. Dados Pessoais:",

	'head11privacy' 		=>	"2. Dados Não Pessoais:",

	'head12privacy'		=>	"Divulgação das informações que recolhemos:",

  'head13privacy' 		=>  "1. Dados Pessoais:",

	'head14privacy' 		=>	"2. Dados Não Pessoais:",

	'head15privacy'		=>	"As suas opções:",

  'head16privacy' 		=>  "Exclusões:",

	'head17privacy' 		=>	"Crianças:",

	'head18privacy'		=>	"Ligações para outros websites:",

  'head19privacy' 		=>  "Armazenamento e segurança:",

	'head20privacy' 		=>	"Legislação internacional de privacidade:",

	'head21privacy'		=>	"Programas US-EU & US-Swiss Safe Harbor:",

  'head22privacy' 		=>  "Outros termos e condições:",

	'head23privacy' 		=>	"Alterações a esta Política de Privacidade:",

	'hea24privacy'		=>	"Acesso a Informações:",

  'head25privacy' 		=>  "Retenção e Eliminação:",

	'head26privacy' 		=>	"Contactar o SponzorMe:",

	'head27privacy'		=>	"Contestar Resolução:",

	'text1' 		=>  'Bem-vindo ao SponzorMe. O SponzorMe, Inc. ("Empresa", "nós", "nos" e/ou "nosso") permite que pessoas em todo o mundo planeiem, promovam e vendam bilhetes para qualquer evento. Facilitamos a todos a pesquisa de eventos e a partilha de eventos em que participam, com as pessoas que conhecem. Isto acontece através dos nossos websites e domínios, dos serviços disponíveis nos ou através dos nossos websites e domínios, ou de outra forma prestados por nós, e do software disponível nos ou através dos nossos websites e domínios, ou de outra forma disponibilizado por nós (incluindo as nossas aplicações móveis) (em conjunto designados como "Services").',

	'text2' 		=>  'Esta Política de Privacidade define a nossa política relativamente às informações, incluindo informações de identificação pessoal ("Dados Pessoais"), recolhidas de utilizadores e/ou visitantes dos Serviços (incluindo as referentes aos agentes dos utilizadores e visitantes) ("o utilizador" ou "o seu/a sua"), incluindo (i) utilizadores registados que são organizadores e planeadores de eventos e organizações de caridade ("Organizadores"), (ii) utilizadores que pretendem comprar bilhetes, registar-se ou fazer donativos para eventos (quer sejam gratuitos ou pagos) constantes das listas de Organizadores nos Serviços ("Compradores") e (iii) outros utilizadores ou visitantes Não-organizadores dos Serviços ("outros Não-organizadores").
Encaramos a privacidade dos seus Dados Pessoais e outras informações com a maior seriedade. Por esse motivo, criámos a presente Política de Privacidade. Agradecemos que leia esta Política de Privacidade, pois contém informações importantes sobre os seus Dados Pessoais e outras informações.
Em caso de dúvidas ou questões, não hesite em contactar-nos através da seguinte ligação:https://www.SponzorMe.pt/contact-us.
',
'text3' 		=>  'Ao utilizar os Serviços ou permitir que alguém utilize os Serviços em seu nome, está a consentir que procedamos à receção, utilização, divulgação, transferência e armazenamento, em conformidade com esta Política de Privacidade, de quaisquer Dados Pessoais e outras informações recebidas por nós no âmbito dessa utilização.',
'text4' 		=>  'Quando interage connosco através dos Serviços, podemos recolher Dados Pessoais e outras informações suas, da forma descrita abaixo:',
'text5' 		=>  'Organizadores: Recolhemos Dados Pessoais seus quando fornece essas informações aos Serviços de forma voluntária, como quando se regista para aceder aos Serviços enquanto Organizador, quando nos contacta com questões, responde a um dos nossos inquéritos ou utiliza determinados Serviços. Os Dados Pessoais que podemos recolher incluem mas não se limitam ao seu nome, endereço, endereço de correio eletrónico e outras informações de identificação pessoal. Em alguns casos, podemos recolher informações do seu cartão de crédito (por exemplo, número do cartão de crédito e data de validade, endereço para faturação, etc.), podendo algumas das quais constituir Dados Pessoais, para garantir determinados pagamentos. Além disso, se utilizar os nossos serviços de processamento de pagamentos, recolheremos informações financeiras (por exemplo, informações da sua conta bancária ou um endereço para envio de cheques) conforme necessário para facilitar os pagamentos e informações requeridas para efeitos fiscais (por exemplo, o seu número de identificação fiscal).
Compradores e outros Não-organizadores: Recolhemos Dados Pessoais seus quando fornece essas informações aos Serviços de forma voluntária (incluindo páginas de registo de eventos nos Serviços), como quando se regista para aceder aos Serviços (quer seja como Organizador ou de qualquer outra forma), quando se regista para um evento como Comprador, quando nos contacta com questões, responde a um dos nossos inquéritos ou utiliza determinadas partes dos Serviços. Os Dados Pessoais que poderemos recolher incluem mas não se limitam ao seu nome, endereço, endereço de correio eletrónico, código postal e outras informações de identificação pessoal. Quando se regista para um evento pago, recolhemos informações financeiras (por exemplo, número do cartão de crédito e data de validade, endereço para faturação, etc.), podendo algumas das quais constituir Dados Pessoais. Além disso, os Organizadores podem configurar páginas de registo de eventos para recolher as mais variadas informações de Compradores, relacionadas com o registo para um evento do Organizador existente na lista de Serviços. Se um Comprador fornecer informações, de forma voluntária, relacionadas com o registo para um evento ou outras opções, estas são disponibilizadas para nós e serão armazenadas por nós, em conformidade com esta Política de Privacidade. Além disso, essas informações são enviadas ao Organizador do respetivo evento, em conformidade com a "Divulgação das informações que recolhemos: Organizadores" abaixo indicada.
Ligações para a Política de Privacidade: Tentamos fornecer uma ligação para esta Política de Privacidade no rodapé de cada página dos nossos websites, incluindo as páginas em que os Dados Pessoais são recolhidos, sendo a mesma também disponibilizada em todo o nosso software.',
'text6' 		=>  'Dados Não Identificáveis: Quando interage connosco através dos Serviços, recolhemos determinadas informações não identificáveis ("Dados Não Pessoais"). Os Dados Não Pessoais que recolhemos incluem mas não se limitam a endereços de Protocolo Internet (IP), tipo de browser da Internet, outras características do seu dispositivo e software, nomes de domínios do seu fornecedor de serviços de Internet, a sua localização geográfica aproximada, um registo da sua utilização dos Serviços e a hora de utilização, bem como Dados Pessoais agregados, que não podem ser utilizados especificamente para o identificar. Estas informações, que são recolhidas de forma passiva através de várias tecnologias, não podem, por si só, ser utilizadas especificamente para o identificar. Também recolhemos Dados Não Pessoais (incluindo mas não se limitando a dados do tipo acima descrito) de terceiros. As informações que recolhemos de terceiros podem ser combinadas com as informações que recolhemos.
Dados Pessoais Agregados: Como parte de um esforço contínuo para melhor compreender e servir os utilizadores dos Serviços, realizamos regularmente estudos sobre os dados demográficos, interesses e comportamentos dos clientes, com base em Dados Pessoais e outras informações que recolhemos. Estes estudos poderão ser compilados e analisados de forma agregada e estas informações agregadas não identificam os utilizadores pessoalmente, pelo que são considerados e tratados como Dados Não Pessoais ao abrigo deste Política de Privacidade.',
'text7' 		=>  'Consulte a nossa Política de Cookies, incorporada por referência nesta Política de Privacidade, para obter mais informações sobre a nossa utilização destas tecnologias.',
'text8' 		=>  'Utilizamos os Dados Pessoais que recolhemos da forma estabelecida nesta Política de Privacidade. Podemos utilizar os Dados Pessoais da seguinte forma:
Motivo específico: Se fornecer Dados Pessoais por um determinado motivo, podemos utilizar os Dados Pessoais de forma relacionada com o motivo pelo qual foram fornecidos. Por exemplo, se nos contactou por correio eletrónico, utilizaremos os Dados Pessoais fornecidos para responder à sua questão ou resolver o seu problema e responderemos para o endereço de correio eletrónico de onde provém o contacto.
Acesso e utilização: Se fornecer Dados Pessoais para ter acesso ou utilizar os Serviços ou qualquer funcionalidade dos mesmos, utilizaremos os seus Dados Pessoais para lhe permitir o acesso ou utilização dos Serviços ou funcionalidades e para monitorizar a sua utilização desses Serviços ou funcionalidades. Por exemplo, se fornecer informações de pagamento (tais como, informações referentes à conta bancária ou ao cartão de crédito) aos Serviços para fins de aquisição de bilhetes enquanto Comprador ou para processamento de pagamentos enquanto Organizador, utilizaremos essas informações para facilitar essa aquisição ou processar esses pagamentos.
Fins internos da empresa: We may use your Personal Data for internal business purposes including without limitation to help us improve the content and functionality of the Services, to better understand our users, to improve the Services, to protect against, identify or address wrongdoing, to enforce our Terms of Service, to manage your account and provide you with customer service, and to generally manage the Services and our business.
Marketing: Poderemos utilizar os seus Dados Pessoais para o contactar no futuro, para fins de marketing e publicidade, incluindo, entre outros, para o informar sobre serviços ou eventos que julgamos poderem ser do seu interesse, para desenvolver materiais promocionais ou de marketing e lhe fornecer esses materiais e para apresentar conteúdos e publicidade, nos Serviços ou fora dos Serviços, que julgamos poderem ser relevantes para si. Sobretudo os Organizadores devem ter em conta que podemos utilizar as informações que recebemos ou recolhemos sobre os Compradores (incluindo, entre outros, através da página de registo de um evento do Organizador), em conformidade com os termos desta Política de Privacidade, incluindo da maneira descrita acima.
Correio eletrónico do organizador: Permitimos que os Organizadores utilizem o nosso sistema de correio eletrónico para contactar os Compradores dos seus eventos atuais ou anteriores, pelo que o utilizador pode receber mensagens de correio eletrónico do nosso sistema que sejam provenientes desses Organizadores.
Se pretendermos utilizar quaisquer Dados Pessoais de uma forma não estabelecida nesta Política de Privacidade, será informado antecipadamente dessa utilização, antes ou na data em que os Dados Pessoais forem recebidos ou obteremos o seu consentimento após tal receção, mas antes da respetiva utilização.',
'text9' => 'Visto que os Dados Não Pessoais não podem ser utilizados para o identificar pessoalmente, podemos utilizar essas informações para qualquer fim conforme estabelecido na lei.',
'text10' 		=>  'Não somos uma empresa de venda de Dados Pessoais. Consideramos que essas informações constituem um factor essencial da nossa relação consigo. Por conseguinte, não vendemos os seus Dados Pessoais a terceiros, incluindo outros anunciantes. Todavia, existem circunstâncias em que podemos divulgar, transferir ou partilhar os seus Dados Pessoais com determinadas entidades terceiras, sem aviso prévio, conforme descrevemos abaixo:
Transferências de empresas: No âmbito da estratégia de desenvolvimento da nossa empresa, poderemos vender ou comprar empresas ou ativos. No caso de uma venda, fusão, reorganização, dissolução da empresa ou de uma situação semelhante, os Dados Pessoais poderão fazer parte dos ativos transferidos. O utilizador reconhece e concorda que um sucessor ou comprador da Empresa (ou dos respetivos ativos) continuará a ter o direito de utilizar os seus Dados Pessoais e outras informações, de acordo com os termos desta Política de Privacidade.
Subsidiárias e afiliados: Também podemos partilhar os seus Dados Pessoais com as nossas subsidiárias e/ou afiliados para fins previstos nesta Política de Privacidade. As nossas subsidiárias e afiliados são obrigados a tratar esses Dados Pessoais em conformidade com esta Política de Privacidade.
Agentes, consultores e terceiros: Tal como muitas outras empresas, por vezes fazemos contratos com outras entidades para desempenharem determinadas funções relacionadas com a empresa. Estas funções podem incluir, por exemplo, envio de mensagens informativas, preenchimento de bilhetes, manutenção de bases de dados e processamento de pagamentos. Quando subcontratamos outra empresa para desempenhar estas funções, poderemos fornecer-lhes informações, incluindo Dados Pessoais, no âmbito do desempenho de tais funções.
Organizadores: Quando o utilizador compra bilhetes, se regista ou efetua um donativo para um um evento ou na respetiva página de angariação de fundos nos Serviços, concorda que a SponzorMe forneça os seus Dados Pessoais aos Organizadores de tal evento e respetiva página de angariação de fundos, se tal for aplicável. Para páginas de angariação de fundos, poderemos fornecer as suas informações pessoais à instituição de caridade Organizadora da página e ao Organizador do evento ao qual a página está ligada. Estes Organizadores não estão obrigados a tratar os seus Dados Pessoais de acordo com esta Política de Privacidade. O utilizador concorda que a SponzorMe não é responsável pelas ações destes Organizadores relativamente aos seus Dados Pessoais. É importante que o utilizador reveja as políticas aplicáveis do Organizador do evento (e respetiva página de angariação de fundos, caso seja aplicável) antes de fornecer Dados Pessoais ou outras informações relacionadas com esse evento ou página de angariação de fundos.
Facebook e Outras Ligações de Terceiros: Pode ligar a sua conta SponzorMe às contas que tem em serviços de terceiros como o Facebook, pelo que poderemos recolher, utilizar, revelar, transferir e guardar informações relacionadas com a sua conta junto destes serviços de terceiros em conformidade com esta Política de Privacidade. Por exemplo, se ligar com o Facebook, guardamos a identificação do Facebook, nome, apelido, endereço de correio eletrónico, localização, lista de amigos e imagem do perfil e utilizamo-los para ligar à sua conta do Facebook de modo a oferecer alguma funcionalidade nos Serviços, como, por exemplo, recomendar eventos em que os seus amigos do Facebook estão interessados e partilhar eventos em que está interessado com alguns grupos de pessoas como os seus amigos do Facebook.
Requisitos legais: Poderemos divulgar os seus Dados Pessoais se tal for obrigatório por lei (incluindo, entre outros, em resposta a uma intimação ou pedido de aplicação da lei, tribunal ou agência governamental) ou por acreditarmos de boa fé que tal ação é necessária (i) para cumprimento de uma obrigação legal, (ii) para proteção ou defesa dos nossos direitos, interesses ou propriedade ou dos dos clientes ou utilizadores, (iii) para prevenir, investigar ou identificar possíveis atos ilícitos relacionados com os Serviços, (iv) para tomada de medidas em circunstâncias urgentes, de forma a proteger a segurança pessoal dos utilizadores dos Serviços ou do público ou (v) para proteção de responsabilidade jurídica.',
'text11' 		=>  'Visto que os Dados Não Pessoais não podem ser utilizados para o identificar pessoalmente, podemos divulgar, transferir ou partilhar Dados Não Pessoais para qualquer fim jurídico.',
'text12' 		=>  'Existem várias opções no que diz respeito aos seus Dados Pessoais:
Limitar os Dados Pessoais que fornece: Pode utilizar os Serviços sem fornecer quaisquer Dados Pessoais ou limitando os Dados Pessoais que fornece. Se optar por não fornecer quaisquer Dados Pessoais ou por limitar os Dados Pessoais que fornece, poderá não conseguir utilizar determinadas funcionalidades dos Serviços. Por exemplo, para abrir uma conta, ou para comprar ou vender bilhetes, são necessários o seu nome e endereço de correio eletrónico.
Anulação: Pode optar por "anular" a receção por correio eletrónico da newsletter da Empresa iniciando sessão, clicando em "Conta" e seguindo as instruções para "preferências de correio eletrónico." Pode modificar as suas opções a qualquer altura na sua conta SponzorMe. Caso um Organizador utilize o nosso sistema para lhe enviar mensagens de correio eletrónico, poderá também optar por "anular" a receção dessas comunicações. Tenha em atenção que, se anular a subscrição de receção de mensagens de correio eletrónico de um determinado Organizador, já não receberá as mensagens de correio eletrónico desse Organizador enviadas através do nosso sistema (pode ainda receber mensagens de correio eletrónico desse Organizador por outros meios que não o nosso sistema), contudo, continuará a receber comunicações da SponzorMe e de outros Organizadores em cujos eventos tenha participado ou nos quais esteja registado como participante, bem como de outros que tenham obtido o seu endereço de correio eletrónico. Da mesma forma, caso anule a subscrição das nossas comunicações, continuará a receber comunicações de Organizadores. Assim, poderá ser necessário anular a subscrição de vários correios eletrónicos antes de deixar de receber todas as comunicações. Pode igualmente anular a subscrição de todas as mensagens de correio eletrónico de Organizadores enviadas através do nosso sistema. Pode demorar até 24 horas a processar um pedido de anulação de subscrição. Tenha em atenção que não é possível anular a subscrição de comunicações de atualização sobre os serviços. A única forma de deixar de receber comunicações de Serviço é contactando-nos em https://www.SponzorMe.pt/contact-us e encerrando a sua conta. Ao escolher deixar de receber todas as nossas comunicações ou as enviadas através do nosso sistema, deixará de receber atualizações na sua conta ou nos eventos em que se encontra registado, bem como nos eventos nos quais tenha participado anteriormente, incluindo comunicações relativas a reembolsos. Não recomendamos esta ação, a menos que planeie deixar de utilizar os Serviços, não esteja atualmente registado num evento, não esteja atualmente a organizar um evento e não necessite receber mais comunicações nossas ou através do nosso sistema. Mesmo após cancelar todas as comunicações, conservaremos os seus Dados pessoais e não pessoais, em conformidade com esta Política de privacidade, contudo, os mesmos já não serão utilizados para o contactar. No entanto, os Organizadores que tenham tido acesso aos seus Dados pessoais, em conformidade com esta Política de privacidade, podem continuar a utilizar esses Dados pessoais para o contactar, em conformidade com as suas respetivas políticas de privacidade, não podendo, contudo, utilizar o nosso sistema para o efeito.
Protocolo Do Not Track: Atualmente não participamos em nenhum protocolo "Do Not Track" que nos permita responder a sinais ou outros mecanismos do utilizador relativamente à recolha dos seus Dados Pessoais.',
'text13' => 'Esta Política de Privacidade não se aplica aos Dados Pessoais recolhidos por nós que não tenham sido recolhidos através dos Serviços. Esta Política de Privacidade não se aplica a informações não solicitadas que o utilizador forneça à nossa Empresa ou a outro utilizador ou visitante através dos Serviços ou de quaisquer outros meios. Isto inclui mas não se limita a informações divulgadas em quaisquer áreas públicas dos Serviços, tais como boletins, ideias para novos produtos ou modificações de produtos existentes, cartas de reclamação ou pedidos, avisos da Lei Digital Millennium Copyright Act e outros envios não solicitados (designados em conjunto como "Informações Não Solicitadas"). Todas as Informações Não Solicitadas serão consideradas como dados não confidenciais, pelo que poderemos reproduzir, utilizar, divulgar, distribuir e explorar essas Informações Não Solicitadas sem limitações ou atribuições.',
'text14' => 'Não recolhemos intencionalmente Dados Pessoais de crianças com menos de 13 anos. Se o utilizador tiver menos de 13 anos, não deve enviar Dados Pessoais através dos Serviços. Incentivamos os pais e encarregados de educação a monitorizar a utilização que as crianças fazem da Internet e contribuir para o cumprimento da nossa Política de Privacidade dando instruções às respetivas crianças para que nunca forneçam Dados Pessoais através dos Serviços sem a sua autorização. Se o utilizador tem motivos para crer que uma criança com menos de 13 anos nos forneceu Dados Pessoais através dos Serviços, contactar-nos, e envidaremos todos os esforços para eliminar essas informações das nossas bases de dados.',
'text15' => 'Esta Política de Privacidade aplica-se apenas aos Serviços. Os Serviços podem conter ligações para outros websites não geridos ou controlados por nós (os "Sites de Terceiros"). As políticas e procedimentos aqui descritos não se aplicam aos Sites de Terceiros. As ligações dos Serviços não implicam que aprovemos ou que tenhamos revisto os Sites de Terceiros. Sugerimos que contacte esses sites diretamente para obter informações sobre as respetivas políticas de privacidade.',
'text16' => 'Podemos armazenar os próprios Dados Pessoais ou essas informações podem ser incluídas em bases de dados que são propriedade e cuja manutenção é da responsabilidade dos nossos afiliados, agentes ou prestadores de serviços. Tomamos as medidas que consideremos razoáveis para proteger os Dados Pessoais fornecidos através dos Serviços contra perda, utilização inadequada, acesso não autorizado, divulgação inadvertida, alteração e destruição. Todavia, nenhuma transmissão pela Internet ou por correio eletrónico é completamente segura ou isenta de eros. Em, particular, as mensagens de correio eletrónico enviadas de e para os Serviços podem não ser seguras. Por conseguinte, deve ter um cuidado especial ao decidir que informações nos envia por correio eletrónico. Deve também ter isto em mente quando divulgar Dados Pessoais através da Internet.',
'text17' => 'Se consulta o nosso website de fora dos Estados Unidos da América, deve ter em conta que está a enviar informações (incluindo Dados Pessoais) para os Estados Unidos da América, onde se encontram os nossos servidores. Armazenamos e processamos os seus Dados Pessoais e Dados Não Pessoais em conformidade com a legislação de privacidade dos Estados Unidos da América e com esta Política de Privacidade. Deve ter em conta que a legislação de privacidade nos Estados Unidos da América poderá não ser a mesma e, em alguns casos, poderá oferecer menos proteção, do que a legislação de privacidade do seu país.',
'text18' => "Participamos na US-EU & US-Swiss Safe Harbor Frameworks cobrindo a recolha, utilização e retenção de informações pessoais obtidas nos países membros da União Europeia e na Suíça. A nossa participação significa que auto-certificamos que aderimos aos princípios da Safe Harbor relativamente a avisos, escolha, transferência para terceiros, segurança, integridade, acesso e execução relativas a este tipo de informações pessoais. Para obter mais informações sobre estas estruturas e a nossa participação nas mesmas, visite o website do US Department of Commerce's Safe Harbor. Se tiver questões relacionadas com a nossa participação, contacte o nosso SponzorMe Safe Harbor Privacy Contact em SponzorMe, Inc., Attn: Privacy Officer, 2081 Center Street , CA 94704, EUA ou por correio eletrónico emprivacy@SponzorMe.com.",
'text19' => 'O acesso e a utilização que fizer dos Serviços estão sujeitos aos Termos de Serviço do SponzorMe. Se utiliza as interfaces de programação de aplicações do SponzorMe (as "APIs do SponzorMe"), está sujeito(a) aos Termos de Utilização de APIs do SponzorMe.',
'text20' => 'Os Serviços e a nossa Empresa podem estar sujeitos a alterações ocasionais. Como tal, por vezes, poderá ser necessário alterarmos esta Política de Privacidade. Reservamo-nos o direito de, se assim o entendermos, atualizar ou alterar esta Política de Privacidade em qualquer altura (coletivamente referidas como "Alterações"). As Alterações a esta Política de Privacidade serão publicadas no Website SponzorMe com a alteração da data de "Última Atualização" na parte superior desta Política de Privacidade. Em determinadas circunstâncias, a SponzorMe poderá, mas não está obrigada a, fornecer ao utilizador um aviso adicional relativamente a tais Alterações, através de mensagens de correio eletrónico ou de notificações no Serviço. As Alterações tornam-se efetivas 30 dias após a data de "Última Atualização" ou de outra data em conformidade com qualquer outro aviso ao utilizador. Agradecemos que reveja esta política periodicamente e sobretudo antes de fornecer quaisquer Dados Pessoais. A última atualização a esta Política de Privacidade foi efetuada na data acima indicada. A utilização continuada dos Serviços após quaisquer Alterações a esta Política de Privacidade significa a aceitação dessas Alterações. Se o utilizador não concordar com qualquer das Alterações a esta Política de Privacidade, a única solução será terminar o acesso, pesquisa ou qualquer outra utilização dos Serviços.',
'text21' => 'Os Organizadores podem aceder a e atualizar os respetivos Dados Pessoais guardados pelo site iniciando sessão e visitando a página A Minha Conta. Os Organizadores poderão também contactar-nos diretamente no endereço especificado abaixo relativamente a Dados Pessoais que não estão acessíveis na página A Minha Conta. Os Compradores e outros não Organizadores não dispõem de uma conta formal no SponzorMe, contudo, é possível criar uma conta formal registando-se. Depois do registo, é possível atualizar e aceder aos Dados Pessoais na página A Minha Conta. Os Compradores e outros não Organizadores podem também contactar-nos diretamente com pedidos para atualizar Dados Pessoais no endereço especificado abaixo. Tomaremos as medidas que considerarmos razoáveis para responder a pedidos relacionados com Dados Pessoais no prazo de 30 dias, contudo, poderão ser rejeitados pedidos que não sejam considerados razoáveis (por ex., que exijam esforços desproporcionados ou a introdução de alterações materiais nos nosso sistemas de informações), pouco práticos ou abusivos (por ex., pedidos repetitivos, pedidos feitos de má-fé, pedidos passíveis de comprometer informações de terceiros). Note que poderão ter acesso ou capacidade para atualizar Dados Não Pessoais, muitos dos quais são mantidos na forma agregada.',
'text22' => 'Poderemos reter os seus Dados Pessoais desde que continue a utilizar os Serviços. Poderá fechar a sua conta contactando-nos. Contudo, poderemos reter Dados Pessoais e Dados Não-Pessoais por um período de tempo adicional como é permitido ou obrigatório nos termos da legislação aplicável. Mesmo que os seus Dados Pessoais sejam eliminados poderão permanecer em cópias de segurança ou suportes de arquivo e outros sistemas de informações.',
'text23' => 'Não hesite em nos contactar se tiver dúvidas sobre esta Política de privacidade ou sobre as nossas práticas de informação. Pode contactar-nos escrevendo para http://www.SponzorMe.com/contact-us ou telefonando para o número +1 5104176510',
'text24' => 'Caso tenha uma queixa sobre as práticas de privacidade da SponzorMe deve escrever-nos para SponzorMe, Inc., Attn: Privacy Officer, 2081 Center Street, Berkeley, CA 94704, EUA ou por correio eletrónico paraprivacy@SponzorMe.com. Tomaremos as medidas que considerarmos razoáveis para trabalharmos com o utilizador na tentativa de resolução da queixa. Como parte da nossa participação nas US-EU & US-Swiss Safe Harbor Frameworks, a SponzorMe nomeou a TRUSTe como mecanismo exclusivo de resolução de conflitos para todas as queixas relacionadas com a Safe Harbor Framework. Pode apresentar uma queixa junto da TRUSTe pela Internet aqui, por fax para o número 415-520-3420 ou por correio para o TRUSTe Safe Harbor Compliance Department no endereço listadoaqui, mas em cada caso apenas depois de contactar os nosso Agente de Privacidade com a sua queixa e dando-nos um período de tempo razoável para processar a queixa. Se enviar um fax ou uma carta à TRUSTe para apresentar uma queixa, deve incluir as seguintes informações: o nome da empresa, a alegada violação de privacidade, as informações do contacto e se pretende partilhar os detalhes da queixa com a empresa. Para obter informações sobre a TRUSTe ou a operação do processo de resolução de conflitos da TRUSTe, clique aqui ou solicite estas informações junto da TRUSTe em qualquer um dos endereços listados acima. O processo de resolução de conflitos da TRUSTe será conduzido em inglês.',
);
